### ISSUE TITLE
Támrudak problémája

### ISSUE THREAD

**Issue by xavvior** [varosifak/application#8]
A Támrudak mennyiségének módosítása úgy, hogy ne 1, 2 illetve 4 + támrúd legyen, hanem név szerint
"1-2-Több támrúd".

Értékeket nem szükséges módosítani, ez globális változtatás lesz.

**Comment by aotlsa** [comment]
Feldolgozás alatt.

**Comment by aotlsa** [comment]
Fixed: http://irinyi.cloud:8080/#/c/76/

**Comment by xavvior** [comment]
Thx :)
