### ISSUE TITLE
P.Dávid a kapcsolat menüpontba

### ISSUE THREAD

**Issue by xavvior** [varosifak/application#9]
P.Dávid adatait beírni a kapcsolat menüpontba, mivel ő felel a teljes Webért, ezért később, ha ezzel gond lesz őt kell keresni elsősorban.

**Comment by aotlsa** [comment]
Feldolgozás alatt.

**Comment by aotlsa** [comment]
Fixed: http://irinyi.cloud:8080/#/c/75/

**Comment by xavvior** [comment]
Javítva
